### ISSUE TITLE
No rule to make target needed by 'obj/HIDParser.o' Stop.

### ISSUE THREAD

**Issue by ScorelessPine** [LightningStalker/Splatmeme-Printer#10]
I've been following the readme guide, but when I open a command prompt in the directory and type `make` I receive this error. Previously, I had been getting a separate error which I resolved by downloading a folder named `obj` in the comments of [this reddit post](https://www.reddit.com/r/splatoon/comments/6wabwt/clarification_on_the_using_a_program_to_draw/). The prompt was able to successfully compile `Joystick.c` and seems to have been able to compile `Descriptors.c` and `Image.c`, but seems to have failed afterwards and gives me this error:

```
make: *** No rule to make target `LUFA/Drivers/USB/Class/Common/HIDParser.c', needed by `obj/HIDParser.o'.  Stop.
```

I can provide a full log from open to error of the command prompt if requested.

**Comment by LightningStalker** [comment]
Thanks for letting me know about this.  I have no idea where the `obj` directory went.  It's here on my local clone, so I'll fix that.  That's really weird.

**Comment by ScorelessPine** [comment]
Even after placing the `obj` folder i downloaded in the correct place, however, I still get the error and I can't make the `Joystick.hex` file needed to flash it onto my Arduino though, do you have any idea what could be causing it?

**Comment by LightningStalker** [comment]
`obj` is supposed to be created during compilation.  What OS are you running this on?

**Comment by ScorelessPine** [comment]
I'm on a Windows 10 Laptop.

**Comment by LightningStalker** [comment]
Unfortunately, I do not have Windows 10 to test.  Did you d/l the latest Atmel toolchain?

**Comment by ScorelessPine** [comment]
If you're talking about the WinAVR mentioned in the link to the GCC compiler and tools install, then yes. Otherwise, I'm unsure what you're talking about.

**Comment by LightningStalker** [comment]
WinAVR is way out of date.  Try downloading the [latest AVR toolchain](http://www.atmel.com/tools/atmelavrtoolchainforwindows.aspx).

**Comment by LightningStalker** [comment]
So did it work?

**Comment by ScorelessPine** [comment]
That website requires me to create an account or submit a form as a guest in order to download the Windows Installer. It says I will receive an email to confirm my registration, so I will have to get back to you whenever that happens. In the meantime, before installing it, from a fresh download of Splatmeme-Printer-master, running make gives me this log of info to the command console: https://pastebin.com/J3BX7Dhs

**Comment by ScorelessPine** [comment]
I'm pretty sure it's a different error than I was getting before, but I don't really know why or how.

**Comment by LightningStalker** [comment]
Yea that compiler is way too old. Showing dates from 2008 and 2010

Whenever Atmel sends the link let me know how it goes.

**Comment by LightningStalker** [comment]
Yea that compiler is way too old, showing dates from 2008 and 2010

Whenever Atmel sends the link let me know how it goes.

**Comment by LightningStalker** [comment]
If it still doesn't work, also try [this gbatemp thread](http://gbatemp.net/threads/how-to-use-shinyquagsires-splatoon-2-post-printer.479497/) and let me know how it goes.

**Comment by ScorelessPine** [comment]
Funny, I actually was just reading the same thing reposted to reddit by the same person. That thread doesn't detail how to use it with the Arduino Uno board, which is the only one that I have. Is there anywhere else that I could download the Toolchain? I still haven't gotten an email back from them and I tried filling out a form as a guest _and_ registering for an account.

**Comment by LightningStalker** [comment]
Try using a [BugMeNot](http://bugmenot.com/view/atmel.com).

**Comment by ScorelessPine** [comment]
Yo I had no idea that was a thing. Worked like a charm, thanks. Ill get back to you whether it worked or not in a bit.

**Comment by ScorelessPine** [comment]
Okay I'm having a totally separate problem now, which I think has to do with the fact that I installed the Mingw32 thing again and now when I type `make`, windows can't recognize it as a command, what do I need to add to the system environment variables in order to make it work correctly? I think I have everything else done right, so if I can get this to work, i think the rest should work right too.

**Comment by ScorelessPine** [comment]
I tried following the gbatemp thread you linked anyway, but it seems i screwed something up when I tried to install MinGW.

**Comment by LightningStalker** [comment]
Try doing a restart.  Environment variables were probably changed.

**Comment by ScorelessPine** [comment]
I'm still getting the `make` error after restarting.

**Comment by ScorelessPine** [comment]
OKAY I FINALLY FIGURED IT OUT. It's partly because I'm stupid and didn't read the same thing correctly 5 times, partly because I needed to install other things.

The part I'm stupid about is that I wasn't adding directories to `PATH`, I was adding environment variables instead. After I (correctly) added the bin directories of MinGW, AVR8 toolchain, and  python 2.7 to the `PATH` and ran `make all` I finally built the `Joystick.hex` I so terribly wanted.

Problem finally solved, so I'm closing the issue. Thanks for the help!

**Comment by LightningStalker** [comment]
Yw, great to hear you got it working.

It's supposed to build the `all` target by default, but on Windows who knows?

Make sure to read the entire `README.md` as well.

**Comment by LightningStalker** [comment]
Oh and one further question if you don't mind: what happens when you run `make` without any arguments or run `make with-alert`?

**Comment by ScorelessPine** [comment]
Running `make` without any arguments also seems to sucessfully build Joystick.hex, and `make with-alert` seems to do the same thing. I can't tell a difference between the 3 commands.

**Comment by LightningStalker** [comment]
FYI, `all` is the default target.  Running `make` without arguments should be the same as `make all`.  The `with-alert` target compiles in the end-of-print alert.  See README.md for more info.
