### ISSUE TITLE
just make failures in general

### ISSUE THREAD

**Issue by s626ch** [LightningStalker/Splatmeme-Printer#16]
i have absolutely no idea what im doing, using an arduino uno r3 board, im 50% sure i have the files in the right places.
folder with both lufa and the printer folder
![image](https://user-images.githubusercontent.com/22896890/51431096-34992c80-1bf2-11e9-8b5b-9bbf21b118c0.png)
printer folder
![image](https://user-images.githubusercontent.com/22896890/51431119-74f8aa80-1bf2-11e9-8565-1b11dd77fa8b.png)
[redacted, refer to below screenshot]
ive been trying to get this to work for a few hours now, and haven't found much that has worked

**Comment by s626ch** [comment]
edit: avrtoolchain used instead, this happening
![image](https://user-images.githubusercontent.com/22896890/51431249-382db300-1bf4-11e9-8bc6-62ec312db252.png)

**Comment by LightningStalker** [comment]
This was made to work on the Teensy++. It definitely won't work on an Arduino Uno.

**Comment by s626ch** [comment]
quite a delayed response but uh, thank you.
i have reason to believe that i, at the time, assumed an uno was fine because it was in the github readme.
