### ISSUE TITLE
Issues connecting to OLED (?)

### ISSUE THREAD

**Issue by JMHAVANCE** [LightningStalker/Splatmeme-Printer#19]
I had a weird issue last night when trying to get this to work on my OLED switch.
I have used this in the past to post on Splatoon2 and wanted to try my luck getting it to work in S3. 

I compiled the image.c, make Joystick.hex, import to Teensy and plug it into my new OLED switch.. **but it doesn't try to sync the controllers like normal.**

After trying to debug for a while I grabbed my daughter's (older) switch and decided to give it a shot.. I just plugged the Teensy in and it works.

Same code compiled on the Teensy, same switch Dock.. only change was switching the Switches.

Anyone else experience issues connecting to OLED switch?

**Comment by salmoooon** [comment]
Have no issue connecting to an OLED here, I'm using an Arduino UNO R3 though

**Comment by geirskogul** [comment]
I'm using a Leonardo/Pro Micro and it's working fine docked for my OLED switch

**Comment by JMHAVANCE** [comment]
Hm, thanks for your feedback guys. I guess I will experiment and try again!

**Comment by JMHAVANCE** [comment]
Looping back on this: I think that the issue is my switch.

I've isolated another issue with the ethernet not working on my new OLED, where switching out with my daughter's switch fixed the issue.. I'm thinking I have received a somewhat defective switch. =x
