### ISSUE TITLE
Pen is changed before the printing

### ISSUE THREAD

**Issue by YozenPL** [LightningStalker/Splatmeme-Printer#6]
Hello,

Before the Teensy is starting to print, pen/brush is changed and program is drawing a "dot".
After that it is changing the position of the cursor and it start drawing.

**Comment by YozenPL** [comment]
Ok I have found that it was trying to sync the controller :)

```
case SYNC_CONTROLLER:
			report_count++;

			if (report_count % 10 == 0 && report_count < 40)
			{
				//ReportData->Button |= SWITCH_L | SWITCH_R;
			}
			else if (report_count == 50)
			{
				report_count = 0;
				//ReportData->Button |= SWITCH_A;
				state = SYNC_POSITION;
			}
			break;
```
Resolved my issue.

**Comment by LightningStalker** [comment]
That's unusual.  The sync dialogue on the Switch should come up when you plug in the dev board.
