### ISSUE TITLE
I use Arduino UNO R3

### ISSUE THREAD

**Issue by tupochang** [LightningStalker/Splatmeme-Printer#7]
I use Arduino UNO R3
But when i edit the makefile setting MCU = atmega16u2
An error occurred
![error](https://user-images.githubusercontent.com/23303373/29670656-e4b485c8-8919-11e7-8a16-4f0645d3f7ca.jpg)

MCU = at90usb1286
Can be compiled successfully

**Comment by LightningStalker** [comment]
I see a couple potential problems right off the bat:
- That is a 7 year old version of `avr-gcc`.
- `Splatmeme-Printer` is inside the `LUFA` folder.

Try using the latest AVR toolchain and read `README.md` very carefully.

**Comment by tupochang** [comment]
Ok, maybe I know where my problem
If follow the steps
GCC Compiler and Tools's Link is very old.
I have to download "avr8-gnu-toolchain"
Copy all folders that cover the "X:\WinAVR-20100110" folder.
Now i can type make, and hit enter to compile.

**Comment by LightningStalker** [comment]
Glad to hear you got it straightened out

**Comment by LightningStalker** [comment]
Closing this
